# Generated by Django 4.2.4 on 2023-08-30 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_tittle', models.CharField(max_length=200)),
                ('income_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_date', models.DateField(auto_now_add=True)),
                ('wallet_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_tittle', models.CharField(max_length=200)),
                ('expense_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_date', models.DateField(auto_now_add=True)),
                ('wallet_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wallet.wallet')),
            ],
        ),
    ]
